export const mockProjects = [
    {
        title: 'Manhattan Wardrobe Supply',
        slug: 'manhattan-wardrobe-supply',
        platform: 'Magento 2',
        url: 'https://wardrobesupplies.com',
        description: 'Magento 2 e-commerce build for a wardrobe supplies retailer, delivering a robust and scalable online shopping experience.',
        heroImage: null,
        gallery: [],
        video: null,
        technologies: ['Magento 2', 'PHP', 'MySQL', 'JavaScript', 'CSS3', 'HTML5'],
        services: ['E-commerce Development', 'Custom Extension Development', 'Performance Optimization'],
        role: 'Web Developer',
        featured: true,
        order: 1,
    },
    {
        title: 'Hot Air Tools',
        slug: 'hot-air-tools',
        platform: 'Magento 2',
        url: 'https://hotairtools.com',
        description: 'Magento 2 e-commerce build for a specialized tools retailer, focused on reliability and user experience.',
        heroImage: null,
        gallery: [],
        video: null,
        technologies: ['Magento 2', 'PHP', 'MySQL', 'JavaScript', 'CSS3', 'HTML5'],
        services: ['E-commerce Development', 'Custom Extension Development', 'Performance Optimization'],
        role: 'Web Developer',
        featured: true,
        order: 2,
    },
    {
        title: "Cherry's Material Handling",
        slug: 'cherrys-material-handling',
        platform: 'Magento 2',
        url: 'https://material-handling.com',
        description: 'Magento 2 e-commerce platform for industrial material handling equipment, built for complex product catalogs.',
        heroImage: null,
        gallery: [],
        video: null,
        technologies: ['Magento 2', 'PHP', 'MySQL', 'JavaScript', 'CSS3', 'HTML5'],
        services: ['E-commerce Development', 'Custom Extension Development'],
        role: 'Web Developer',
        featured: false,
        order: 3,
    },
    {
        title: 'M-Source',
        slug: 'm-source',
        platform: 'Magento 2',
        url: 'https://m-source.com',
        description: 'Magento 2 e-commerce build delivering a streamlined procurement and sourcing platform.',
        heroImage: null,
        gallery: [],
        video: null,
        technologies: ['Magento 2', 'PHP', 'MySQL', 'JavaScript', 'CSS3', 'HTML5'],
        services: ['E-commerce Development', 'Custom Extension Development'],
        role: 'Web Developer',
        featured: false,
        order: 4,
    },
    {
        title: 'US Jewellery Factory',
        slug: 'us-jewellery-factory',
        platform: 'Magento 2',
        url: 'https://usjewelryfactory.com',
        description: 'Magento 2 e-commerce build for a jewelry manufacturer, featuring rich product displays and secure checkout.',
        heroImage: null,
        gallery: [],
        video: null,
        technologies: ['Magento 2', 'PHP', 'MySQL', 'JavaScript', 'CSS3', 'HTML5'],
        services: ['E-commerce Development', 'Custom Extension Development', 'Performance Optimization'],
        role: 'Web Developer',
        featured: true,
        order: 5,
    },
    {
        title: 'Lynks Racing',
        slug: 'lynks-racing',
        platform: 'WordPress',
        url: 'https://lynksracing.com',
        description: 'Custom WordPress development for a racing brand, featuring dynamic content and engaging design.',
        heroImage: null,
        gallery: [],
        video: null,
        technologies: ['WordPress', 'PHP', 'JavaScript', 'CSS3', 'HTML5', 'MySQL'],
        services: ['WordPress Development', 'Custom Theme Development', 'Performance Optimization'],
        role: 'Web Developer',
        featured: true,
        order: 6,
    },
    {
        title: 'Sweat Heaven',
        slug: 'sweat-heaven',
        platform: 'WordPress',
        url: 'https://sweatheaven.com',
        description: 'Custom WordPress development for a fitness and wellness brand, with optimized performance and clean UX.',
        heroImage: null,
        gallery: [],
        video: null,
        technologies: ['WordPress', 'PHP', 'JavaScript', 'CSS3', 'HTML5', 'MySQL'],
        services: ['WordPress Development', 'Custom Theme Development'],
        role: 'Web Developer',
        featured: false,
        order: 7,
    },
    {
        title: 'First Seed Fund',
        slug: 'first-seed-fund',
        platform: 'WordPress',
        url: 'https://firstseedfund.com',
        description: 'Custom WordPress development for a venture capital firm, presenting a professional and trustworthy digital presence.',
        heroImage: null,
        gallery: [],
        video: null,
        technologies: ['WordPress', 'PHP', 'JavaScript', 'CSS3', 'HTML5', 'MySQL'],
        services: ['WordPress Development', 'Custom Theme Development', 'Technical SEO'],
        role: 'Web Developer',
        featured: false,
        order: 8,
    },
    {
        title: 'Forget Me Not Photos',
        slug: 'forget-me-not-photos',
        platform: 'Webflow',
        url: 'https://forgetmenotphotos.com',
        description: 'Webflow website development for a photography studio, emphasizing visual storytelling and elegant design.',
        heroImage: null,
        gallery: [],
        video: null,
        technologies: ['Webflow', 'HTML5', 'CSS3', 'JavaScript'],
        services: ['Webflow Development'],
        role: 'Web Developer',
        featured: true,
        order: 9,
    },
];

export const mockExperience = [
    {
        company: 'Tekglide',
        position: 'Web Developer — WordPress & Magento 2',
        startDate: 'September 2023',
        endDate: 'Present',
        description: 'Building custom Magento 2 extensions, WordPress themes and plugins. Owning projects from analysis through deployment.',
        responsibilities: [
            'Building custom Magento 2 extensions and extending platform functionality',
            'Improving user experience and providing technical support to clients',
            'Diagnosing complex production issues on live websites',
            'Owning projects from analysis through deployment',
            'Designing, coding, debugging, testing, documenting and deploying',
            'Improving website speed, stability and caching strategies',
            'Developing custom WordPress themes and plugins',
            'Optimizing page-load performance and auditing plugin bloat',
        ],
        technologies: ['Magento 2', 'WordPress', 'PHP', 'JavaScript', 'MySQL', 'CSS3', 'HTML5'],
        order: 3,
    },
    {
        company: 'Probyte Pvt Ltd',
        position: 'Frontend Developer — Internship',
        startDate: 'June 2021',
        endDate: 'July 2022',
        description: 'Built responsive web interfaces across mobile and desktop, working with modern JavaScript frameworks.',
        responsibilities: [
            'Built responsive web interfaces for mobile and desktop',
            'Worked with HTML, CSS, JavaScript and modern frameworks',
            'Collaborated with senior developers and participated in code reviews',
        ],
        technologies: ['HTML5', 'CSS3', 'JavaScript'],
        order: 2,
    },
    {
        company: 'Saify Link Technology',
        position: 'WordPress Developer',
        startDate: 'May 2021',
        endDate: 'September 2021',
        description: 'Customized WordPress themes and admin components, building commercial websites with cross-browser compatibility.',
        responsibilities: [
            'Customized WordPress admin components and themes',
            'Built commercial websites maintaining coding standards',
            'Ensured cross-browser compatibility',
            'Collaborated with design and development teams',
        ],
        technologies: ['WordPress', 'PHP', 'JavaScript', 'CSS3', 'HTML5'],
        order: 1,
    },
];

export const mockSkills = [
    // E-commerce
    { name: 'Magento 2', category: 'E-commerce', order: 1 },
    { name: 'Shopify', category: 'E-commerce', order: 2 },
    { name: 'WooCommerce', category: 'E-commerce', order: 3 },

    // Development
    { name: 'PHP', category: 'Development', order: 1 },
    { name: 'JavaScript', category: 'Development', order: 2 },
    { name: 'jQuery', category: 'Development', order: 3 },
    { name: 'HTML5', category: 'Development', order: 4 },
    { name: 'CSS3', category: 'Development', order: 5 },
    { name: 'AJAX', category: 'Development', order: 6 },
    { name: 'JSON', category: 'Development', order: 7 },
    { name: 'XML', category: 'Development', order: 8 },

    // Backend / Data
    { name: 'Node.js', category: 'Backend / Data', order: 1 },
    { name: 'Express.js', category: 'Backend / Data', order: 2 },
    { name: 'MySQL', category: 'Backend / Data', order: 3 },
    { name: 'MongoDB', category: 'Backend / Data', order: 4 },
    { name: 'Linux', category: 'Backend / Data', order: 5 },
    { name: 'Git / GitHub', category: 'Backend / Data', order: 6 },
    { name: 'APIs', category: 'Backend / Data', order: 7 },
];

export const mockServices = [
    { title: 'Magento 2 Development', description: 'Custom extensions, theme development and end-to-end Magento 2 e-commerce solutions built for scale.', order: 1 },
    { title: 'WordPress Development', description: 'Bespoke WordPress themes, plugins and content-managed websites tailored to business needs.', order: 2 },
    { title: 'Custom Theme Development', description: 'Pixel-perfect, performance-optimized themes crafted from design mockups to production code.', order: 3 },
    { title: 'Custom Plugin Development', description: 'Purpose-built plugins and extensions that extend platform functionality without bloat.', order: 4 },
    { title: 'E-commerce Development', description: 'Revenue-ready online stores with secure checkout, inventory management and conversion-focused UX.', order: 5 },
    { title: 'API Integration', description: 'Connecting platforms, payment gateways, shipping providers and third-party services through robust APIs.', order: 6 },
    { title: 'Performance Optimization', description: 'Page speed audits, caching strategy, code optimization and Core Web Vitals improvements.', order: 7 },
    { title: 'Technical SEO', description: 'Structured data, site architecture, crawlability and on-page SEO for better search visibility.', order: 8 },
    { title: 'Website Maintenance & Debugging', description: 'Ongoing production support, bug fixing, security patching and legacy code troubleshooting.', order: 9 },
];
